module.exports = {
  tt0084787: {
    imdbID: "tt0084787",
    Title: "The Thing",
    Released: "1982-06-25",
    Runtime: 109,
    Genres: ["Horror", "Mystery", "Sci-Fi"],
    Directors: ["John Carpenter"],
    Writers: ["Bill Lancaster", "John W. Campbell Jr."],
    Actors: ["Kurt Russell", "Wilford Brimley", "Keith David"],
    Plot: "A research team in Antarctica is hunted by a shape-shifting alien that assumes the appearance of its victims.",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BNGViZWZmM2EtNGYzZi00ZDAyLTk3ODMtNzIyZTBjN2Y1NmM1XkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_SX300.jpg",
    Metascore: 57,
    imdbRating: 8.2,
  },
  tt0120737: {
    imdbID: "tt0120737",
    Title: "The Lord of the Rings: The Fellowship of the Ring",
    Released: "2001-12-19",
    Runtime: 178,
    Genres: ["Action", "Adventure", "Drama"],
    Directors: ["Peter Jackson"],
    Writers: ["J.R.R. Tolkien", "Fran Walsh", "Philippa Boyens"],
    Actors: ["Elijah Wood", "Ian McKellen", "Orlando Bloom"],
    Plot: "A meek Hobbit from the Shire and eight companions set out on a journey to destroy the powerful One Ring and save Middle-earth from the Dark Lord Sauron.",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BN2EyZjM3NzUtNWUzMi00MTgxLWI0NTctMzY4M2VlOTdjZWRiXkEyXkFqcGdeQXVyNDUzOTQ5MjY@._V1_SX300.jpg",
    Metascore: 92,
    imdbRating: 8.8,
  },
  tt0085959: {
    imdbID: "tt0085959",
    Title: "The Meaning of Life",
    Released: "1983-03-31",
    Runtime: 107,
    Genres: ["Comedy", "Musical"],
    Directors: ["Terry Jones", "Terry Gilliam"],
    Writers: ["Graham Chapman", "John Cleese", "Terry Gilliam"],
    Actors: ["John Cleese", "Terry Gilliam", "Eric Idle"],
    Plot: "The comedy team takes a look at life in all of its stages in their own uniquely silly way.",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BZWJkNGY5MDAtYmVkMy00NzdiLTk5MzctMzA0MjMxMDY2NGYwXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg",
    Metascore: 72,
    imdbRating: 7.5,
  },
  tt0107048: {
    imdbID: "tt0107048",
    Title: "Groundhog Day",
    Released: "1993-02-12",
    Runtime: 101,
    Genres: ["Comedy", "Drama", "Fantasy"],
    Directors: ["Harold Ramis"],
    Writers: ["Danny Rubin", "Harold Ramis"],
    Actors: ["Bill Murray", "Andie MacDowell", "Chris Elliott"],
    Plot: "A narcissistic, self-centered weatherman finds himself in a time loop on Groundhog Day, and the day keeps repeating until he gets it right.",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BZWIxNzM5YzQtY2FmMS00Yjc3LWI1ZjUtNGVjMjMzZTIxZTIxXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg",
    Metascore: 72,
    imdbRating: 8.1,
  },
  tt0124315: {
    imdbID: "tt0124315",
    Title: "The Cider House Rules",
    Released: "2000-01-07",
    Runtime: 126,
    Genres: ["Drama", "Romance"],
    Directors: ["Lasse Hallström"],
    Writers: ["John Irving"],
    Actors: ["Tobey Maguire", "Charlize Theron", "Michael Caine"],
    Plot: "A compassionate young man, raised in an orphanage and trained to be a doctor there, decides to leave to see the world.",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BNmY5YzA4OTQtOTQzZS00NDZmLTlhNzQtNzk5NTIyZWE2ZjVkXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg",
    Metascore: 75,
    imdbRating: 7.4,
  },
  tt0248808: {
    imdbID: "tt0248808",
    Title: "For the Birds",
    Released: "2001-11-02",
    Runtime: 3,
    Genres: ["Animation", "Short", "Comedy"],
    Directors: ["Ralph Eggleston"],
    Writers: ["Ralph Eggleston"],
    Actors: ["Ralph Eggleston"],
    Plot: "A group of snooty birds roosting on a telephone wire get their just deserts when a goofy bird drops in.",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BZjBhYzgyY2YtMTBhZS00NWIwLWIyYTgtMzhhYmFhZDNkMTQxXkEyXkFqcGdeQXVyNTE1NjY5Mg@@._V1_SX300.jpg",
    Metascore: 0.1,
    imdbRating: 8.0,
  }
};
